import {
  STATE_CLOSED,
  STATE_CLOSING,
  STATE_OPENED,
  STATE_OPENING,
  STATE_RUNNING,
} from "constants/groupStatus";

export const tableCols = {
  [STATE_OPENING]: {
    group: true,
    teacher_without_start_date: true,
    responsible: true,
    start_date: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
  [STATE_OPENED]: {
    group: true,
    teacher_without_start_date: true,
    responsible: true,
    start_date: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
  [STATE_RUNNING]: {
    group: true,
    teacher: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
  // [STATE_RUNNING]: {
  //   group: true,
  //   teacher: true,
  //   branch: true,
  //   day: true,
  //   note: true,
  //   course: true,
  //   students: true,
  //   new_students: true,
  //   actions: true,
  // },
  [STATE_CLOSING]: {
    group: true,
    teacher: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
  [STATE_CLOSED]: {
    group: true,
    teacher: true,
    updated_at: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
  600: {
    group: true,
    teacher: true,
    updated_at: true,
    branch: true,
    day: true,
    note: true,
    course: true,
    students: true,
    new_students: true,
    actions: true,
  },
};
