export const ONLINE_PAYMENT_SERVICE_UZUM_ACTIVE = 13000;
export const ONLINE_PAYMENT_SERVICE_PAYME_ACTIVE = 13100;
export const ONLINE_PAYMENT_SERVICE_CLICK_ACTIVE = 13200;
export const ONLINE_PAYMENT_SERVICE_PLUM_ACTIVE = 13300;
export const INTERNAL_ONLINE_PAYMENT_IS_ACTIVE = 13400;
