export const PAGE_VISITS = {
  can_visit_schedule_page: "can_visit_schedule_page",
  can_visit_stock_page: "can_visit_stock_page",
  can_visit_observation_page: "can_visit_observation_page",
  can_visit_created_student_page: "can_visit_created_student_page",
  can_see_fallible_student_list: "can_see_fallible_student_list",
  can_visit_leads_page: "can_visit_leads_page",
  can_visit_students_waiting_list_page: "can_visit_students_waiting_list_page",
  can_visit_students_new_students_page: "can_visit_students_new_students_page",
  can_visit_students_active_students_page:
    "can_visit_students_active_students_page",
  can_visit_exam_dates_page: "can_visit_exam_dates_page",
  can_visit_exam_results_page: "can_visit_exam_results_page",
  can_take_payment_without_tax_device_connection:
    "can_take_payment_without_tax_device_connection",
  can_visit_students_archived_page: "can_visit_students_archived_page",
  can_visit_student_birthday_page: "can_visit_student_birthday_page",
  can_visit_groups_page: "can_visit_groups_page",
  can_visit_hr_page: "can_visit_hr_page",
  can_visit_academic_resource_page: "can_visit_academic_resource_page",
  can_visit_academic_resource_ars_page: "can_visit_academic_resource_ars_page",
  can_visit_academic_resource_exam_page:
    "can_visit_academic_resource_exam_page",
  can_visit_sms_black_list_page: "can_visit_sms_black_list_page",
  can_visit_academic_resource_attendance_control_page:
    "can_visit_academic_resource_attendance_control_page",
  can_visit_academic_resource_absent_students_page:
    "can_visit_academic_resource_absent_students_page",
  can_visit_finance_transactions_page: "can_visit_finance_transactions_page",
  can_visit_finance_debtors_page: "can_visit_finance_debtors_page",
  can_visit_finance_student_balance_page:
    "can_visit_finance_student_balance_page",
  can_visit_finance_payment_statistics_page:
    "can_visit_finance_payment_statistics_page",
  can_visit_finance_salary_page: "can_visit_finance_salary_page",
  can_visit_finance_cash_flow_page: "can_visit_finance_cash_flow_page",
  can_visit_analytics_page: "can_visit_analytics_page",
  can_visit_secret_client_page: "can_visit_secret_client_page",
  can_visit_events_page: "can_visit_events_page",
  can_visit_tasks_page: "can_visit_tasks_page",
  can_visit_statistics_dashboard_page: "can_visit_statistics_dashboard_page",
  can_visit_statistics_podo_list_page: "can_visit_statistics_podo_list_page",
  can_visit_statistics_freshman_page: "can_visit_statistics_freshman_page",
  can_visit_statistics_losts_page: "can_visit_statistics_losts_page",
  can_visit_statistics_teacher_lost_page:
    "can_visit_statistics_teacher_lost_page",
  can_visit_settings_company_settings_page:
    "can_visit_settings_company_settings_page",
  can_visit_settings_staff_settings_page:
    "can_visit_settings_staff_settings_page",
  can_visit_settings_finance_settings_page:
    "can_visit_settings_finance_settings_page",
  can_visit_settings_academic_settings_page:
    "can_visit_settings_academic_settings_page",
  can_visit_settings_sms_settings_page: "can_visit_settings_sms_settings_page",
  can_visit_settings_holidays_page: "can_visit_settings_holidays_page",
  can_visit_settings_documents_page: "can_visit_settings_documents_page",
  can_transfer_student: "can_transfer_student",
  can_add_contact_to_group: "can_add_contact_to_group",
  can_visit_create_role_page: "can_visit_create_role_page",
  can_visit_ielts_practicum_page: "can_visit_ielts_practicum_page",
  can_visit_black_list_students_page: "can_visit_black_list_students_page",
  can_visit_settings: "can_visit_settings",
  can_visit_finance: "can_visit_finance",
  can_visit_students: "can_visit_students",
  can_see_dashboard_kpi_total: "can_see_dashboard_kpi_total",
  can_visit_call_settings: "can_visit_call_settings",
  can_visit_kpi_statistics_page: "can_visit_kpi_statistics_page",
  can_see_sms_delivery: "can_see_sms_delivery",
  can_see_red_list: "can_see_red_list",
  can_visit_red_lis_page: "can_visit_red_lis_page",
  can_visit_academic_resource_control_page:
    "can_visit_academic_resource_control_page",
  can_visit_ranking_page: "can_visit_ranking_page",
  can_visit_academic_fallible_list_page:
    "can_visit_academic_fallible_list_page",
};
export const COMPONENTS_VIEWS = {
  can_see_debt_statistics: "can_see_debt_statistics",
  can_view_potential_groups: "can_view_potential_groups",
  can_clear_group_students_note: "can_clear_group_students_note",
  admin_can_update_product: "admin_can_update_product",
  admin_can_see_student_referrals: "admin_can_see_student_referrals",
  admin_can_create_category: "admin_can_create_category",
  can_call_user: "can_call_user",
  can_manage_lead_tab: "can_manage_lead_tab",
  can_see_dashboard_own_group: "can_see_dashboard_own_group",
  can_delete_lead_tab: "can_delete_lead_tab",
  can_use_red_balance: "can_use_red_balance",
  can_see_dashboard_all_lead: "can_see_dashboard_all_lead",
  can_see_call_request_notification: "can_see_call_request_notification",
  can_change_hired_date: "can_change_hired_date",
  can_see_podo_requests: "can_see_podo_requests",
  can_finance_payment_for_test: "can_finance_payment_for_test",
  can_manage_vacation_slots: "can_manage_vacation_slots",
  can_view_payment_statistics: "can_view_payment_statistics",
  can_see_lead: "can_see_lead",
  can_manage_potential_fail: "can_manage_potential_fail",
  can_delete_student_avatar: "can_delete_student_avatar",
  can_manage_user_label: "can_manage_user_label",
  can_see_dashboard_own_branch_waiting_list:
    "can_see_dashboard_own_branch_waiting_list",
  can_see_dashboard_own_branch_student_flow:
    "can_see_dashboard_own_branch_student_flow",
  can_see_dashboard_own_branch_income: "can_see_dashboard_own_branch_income",
  can_see_dashboard_own_branch_student: "can_see_dashboard_own_branch_student",
  can_see_dashboard_own_branch_new_student:
    "can_see_dashboard_own_branch_new_student",
  can_see_dashboard_own_branch_teacher_lost:
    "can_see_dashboard_own_branch_teacher_lost",
  can_see_dashboard_own_own_branch_kpi: "can_see_dashboard_own_own_branch_kpi",
  can_see_dashboard_own_branch_staff_motivation:
    "can_see_dashboard_own_branch_staff_motivation",
  can_see_dashboard_own_branch_sms: "can_see_dashboard_own_branch_sms",
  can_see_free_place_of_group: "can_see_free_place_of_group",
  can_see_dashboard_own_new_student: "can_see_dashboard_own_new_student",
  can_see_dashboard_own_lifecycle: "can_see_dashboard_own_lifecycle",
  can_see_dashboard_own_call: "can_see_dashboard_own_call",
  can_see_dashboard_own_income: "can_see_dashboard_own_income",
  can_see_dashboard_own_staff_motivation:
    "can_see_dashboard_own_staff_motivation",
  can_see_dashboard_own_role_kpi: "can_see_dashboard_own_role_kpi",
  can_see_dashboard_own_student_flow: "can_see_dashboard_own_student_flow",
  can_see_dashboard_own_student: "can_see_dashboard_own_student",
  can_see_dashboard_own_sms: "can_see_dashboard_own_sms",
  can_see_dashboard_own_teacher_lost: "can_see_dashboard_own_teacher_lost",
  can_see_dashboard_own_waiting_list: "can_see_dashboard_own_waiting_list",
  can_see_dashboard_own_lead: "can_see_dashboard_own_lead",
  can_see_dashboard_kpi_total_by_all_role:
    "can_see_dashboard_kpi_total_by_all_role",
  send_sms_red_list: "send_sms_red_list",
  can_export_phone_list: "can_export_phone_list",
  can_manage_waiting_students: "can_manage_waiting_students",
  can_send_sms_to_waiting_list_students:
    "can_send_sms_to_waiting_list_students",
  can_see_student_payment: "can_see_student_payment",
  can_see_sms_black_list: "can_see_sms_black_list",
  can_filter_lead_by_created_by: "can_filter_lead_by_created_by",
  can_manage_lead: "can_manage_lead",
  can_filter_student_by_created_by: "can_filter_student_by_created_by",
  can_created_student: "can_created_student",
  can_create_user: "can_create_user",
  can_see_banned_students: "can_see_banned_students",
  can_manage_banned_student: "can_manage_banned_student",
  can_send_sms_to_students: "can_send_sms_to_students",
  can_manage_reception_students: "can_manage_reception_students",
  can_send_sms_from_list: "can_send_sms_from_list",
  can_send_sms_archived_students: "can_send_sms_archived_students",
  can_send_sms: "can_send_sms",
  can_create_group: "can_create_group",
  can_create_sms_black_list: "can_create_sms_black_list",
  can_transfer_student: "can_transfer_student",
  can_add_contact_to_group: "can_add_contact_to_group",
  can_manage_group: "can_manage_group",
  can_filter_by_branch: "can_filter_by_branch",
  can_filter_all_day: "can_filter_all_day",
  can_create_transaction: "can_create_transaction",
  can_create_expense: "can_create_expense",
  can_manage_transaction: "can_manage_transaction",
  can_manage_money_back: "can_manage_money_back",
  can_manage_salary: "can_manage_salary",
  can_manage_company_settings: "can_manage_company_settings",
  can_manage_staff_settings: "can_manage_staff_settings",
  can_manage_finance_settings: "can_manage_finance_settings",
  can_manage_academic_settings: "can_manage_academic_settings",
  can_manage_sms_settings: "can_manage_sms_settings",
  can_manage_holiday_settings: "can_manage_holiday_settings",
  can_manage_document_settings: "can_manage_document_settings",
  can_see_dashboard_lead_statistics: "can_see_dashboard_lead_statistics",
  can_see_dashboard_waiting_list_statistics:
    "can_see_dashboard_waiting_list_statistics",
  can_see_dashboard_freshman_lost_total:
    "can_see_dashboard_freshman_lost_total",
  can_see_dashboard_income_total: "can_see_dashboard_income_total",
  can_see_dashboard_student_statistics: "can_see_dashboard_student_statistics",
  can_see_dashboard_new_student_statistics:
    "can_see_dashboard_new_student_statistics",
  can_see_dashboard_teacher_lost_total: "can_see_dashboard_teacher_lost_total",
  can_see_dashboard_kpi_total: "can_see_dashboard_kpi_total",
  can_see_dashboard_staff_motivation_total:
    "can_see_dashboard_staff_motivation_total",
  can_see_dashboard_sms_statistics: "can_see_dashboard_sms_statistics",
  can_see_dashboard_call_statistics: "can_see_dashboard_call_statistics",
  can_see_all_life_cycle: "can_see_all_life_cycle",
  can_manage_rbac_assignment: "can_manage_rbac_assignment",
  can_edit_rbac_role: "can_edit_rbac_role",
  can_view_student: "can_view_student",
  can_view_group: "can_view_group",
  can_see_attendance_control: "can_see_attendance_control",
  can_see_group_attendance: "can_see_group_attendance",
  can_see_all_created_by_freshmen: "can_see_all_created_by_freshmen",
  can_change_group_note: "can_change_group_note",
  can_change_exam_score: "can_change_exam_score",
  can_change_student_note: "can_change_student_note",
  can_filter_default_all_new_students: "can_filter_default_all_new_students",
  can_take_payment_student: "can_take_payment_student",
  can_create_expense_with_bank: "can_create_expense_with_bank",
  can_create_expense_old_month: "can_create_expense_old_month",
  can_create_income_old_month: "can_create_income_old_month",
  can_only_use_source_community_manager:
    "can_only_use_source_community_manager",
};
