import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Interface, IPayload, IUIStore } from "./type";

const initialData: Interface = {
  open: false,
  data: {},
};
const initialState: IUIStore = {
  payment: initialData,
  changeTeacher: initialData,
  stopping: initialData,
  returnModal: initialData,
  slotCreateModal: initialData,
  createVacationModal: initialData,
  continueModal: initialData,
  attend: initialData,
  returnMoneyCheckModal: initialData,
  transferBack: initialData,
  debtorsListModal: initialData,
  incomeProductName: initialData,
  createTransaction: initialData,
  groupStudentsList: initialData,
  requestConfirmModal: initialData,
  deleteModal: initialData,
  block: initialData,
  createTask: initialData,
  createTaskCategory: initialData,
  taskView: initialData,
  taskUsers: initialData,
  backToWaiting: initialData,
  group: initialData,
  removeCategory: initialData,
  createExpense: initialData,
  leaveDissatisfaction: initialData,
  confirmRestoreTaskCategory: initialData,
  rateTaskModal: initialData,
  groupSms: initialData,
  transactionPayModal: initialData,
  correction: initialData,
  salaryDetails: initialData,
  addBonus: initialData,
  financeConfig: initialData,
  createRoom: initialData,
  candidateCreate: initialData,
  deleteCourse: initialData,
  groupTypeModal: initialData,
  levelModal: initialData,
  checkPassword: initialData,
  dayModal: initialData,
  deleteGroupType: initialData,
  deleteLevel: initialData,
  deleteLessonDay: initialData,
  createCourse: initialData,
  holiday: initialData,
  deleteHoliday: initialData,
  groupNote: initialData,
  staffCreate: initialData,
  blackListPrint: initialData,
  runningTypeModal: initialData,
  printSalaryDetails: initialData,
  addToGroupModal: initialData,
  podo: initialData,
  incomeCheckPreview: initialData,
  paymentCheckSecond: initialData,
  unban: initialData,
  unblock: initialData,
  source: initialData,
  deleteSource: initialData,
  divideExpense: initialData,
  changePassword: initialData,
  new_students_stop: initialData,
  changeStartDate: initialData,
  takeGroup: initialData,
  deleteGroup: initialData,
  updateStudentFlow: initialData,
  lifeCycle: initialData,
  passedStudents: initialData,
  productAndService: initialData,
  deleteProductAndService: initialData,
  operator: initialData,
  deleteOperator: initialData,
  ban: initialData,
  transferLead: initialData,
  selfSms: initialData,
  paymentRequest: initialData,
  moveTransfer: initialData,
  complaint: initialData,
  deleteTransaction: initialData,
  deleteExpense: initialData,
  paymentTransaction: initialData,
  absModal: initialData,
  redListDownload: initialData,
  coverTeacher: initialData,
  deleteCoverTeacher: initialData,
  conditionalPass: initialData,
  examAttendance: initialData,
  archiveLifeCycle: initialData,
  officeHours: initialData,
  profileSalary: initialData,
  registeredLead: initialData,
  freshmanForProfile: initialData,
  confirmLogout: initialData,
  deleteLeadTab: initialData,
  addLeadTab: initialData,
  deleteLead: initialData,
  addLead: initialData,
  transactionLifeCycle: initialData,
  candidateModal: initialData,
  vacancyConfig: initialData,
  rejectCandidate: initialData,
  absCandidateModal: initialData,
  meetingCandidateModal: initialData,
  approveCandidate: initialData,
  candidateLifecycle: initialData,
  mergeCandidate: initialData,
  checkList: initialData,
  addDocumentTab: initialData,
  deleteDocumentTab: initialData,
  groupLifeCycle: initialData,
  dismissStaff: initialData,
  repositionStaff: initialData,
  candidateSMS: initialData,
  confirmFileDelete: initialData,
  dismissDocGenerate: initialData,
  docGenerate: initialData,
  rewardCancel: initialData,
  rewardGive: initialData,
  rewardApprove: initialData,
  rewardRestore: initialData,
  generateCandidateDetails: initialData,
  stockCategory: initialData,
  stockProduct: initialData,
  stockArrival: initialData,
  stockDeparture: initialData,
  stockTransfer: initialData,
  stockChange: initialData,
  cancelDismassal: initialData,
  cancelReposition: initialData,
  labelAddAll: initialData,
  giveAllSalary: initialData,
  labelAllFailedToPodo: initialData,
  taxModal: initialData,
  restrictAccess: initialData,
  potentialFail: initialData,
  observation: initialData,
  deleteObservation: initialData,
  changeObservation: initialData,
  podoRequest: initialData,
  deletePodoRequest: initialData,
  paymentV2: initialData,
  giveStationary: initialData,
  newTransaction: initialData,
  integration: initialData,
  createObservation: initialData,
  responsibleStaff: initialData,
  deleteResponsible: initialData,
  templateModal: initialData,
  deleteTemplate: initialData,
  autoCall: initialData,
  deleteVacation: initialData,
  studentExamResult: initialData,
  studentMockExamResult: initialData,
  stoppingStatusChange: initialData,
  potentialFailRequest: initialData,
  deletePotentialFailRequest: initialData,
  restudyConfig: initialData,
  mockConfig: initialData,
  deleteStudentsNote: initialData,
};

/**
 * Actions and Reducers
 */
const slice = createSlice({
  name: "modals",
  initialState,
  reducers: {
    //modal field name iga qarab stateni o'zgartirish
    toggleModal: (store: IUIStore, { payload }: PayloadAction<IPayload>) => {
      const { key, data }: IPayload = payload;
      store[key] = data;
    },
    resetModals: () => {
      return initialState;
    },
  },
});

export const { toggleModal, resetModals } = slice.actions;

export default slice.reducer;
