export const mockData = [
  {
    id: 146602,
    opened: 1,
    unit_id: 1540,
    opening_date: "2023-03-29",
    unit: {
      id: 1540,
      name: "Verb to be",
      points: 131,
      coins: 131,
      order: 1,
      system_order: 101,
      level: {
        id: 2,
        name: "Elementary",
      },
      parent_unit: {
        id: 1530,
        name: "Unit 1",
        points: 0,
        coins: 0,
        order: 1,
        system_order: 100,
        level: {
          id: 2,
          name: "Elementary",
        },
      },
    },
    student_unit: {
      passed: 0,
      opened: 1,
      unit_id: 1540,
      is_populated: 0,
      collected_points: 0,
      total_points: 0,
      collected_coins: 0,
      total_coins: 0,
      user_id: 103977,
    },
    student_units: [],
  },
  {
    id: 146602,
    opened: 1,
    unit_id: 1540,
    opening_date: "2023-03-29",
    unit: {
      id: 1540,
      name: "Verb to be",
      points: 131,
      coins: 131,
      order: 1,
      system_order: 101,
      level: {
        id: 2,
        name: "Elementary",
      },
      parent_unit: {
        id: 1530,
        name: "Unit 1",
        points: 0,
        coins: 0,
        order: 1,
        system_order: 100,
        level: {
          id: 2,
          name: "Elementary",
        },
      },
    },
    student_unit: {
      passed: 0,
      opened: 1,
      unit_id: 1540,
      is_populated: 0,
      collected_points: 0,
      total_points: 0,
      collected_coins: 0,
      total_coins: 0,
      user_id: 103977,
    },
    student_units: [],
  },
  {
    id: 146602,
    opened: 1,
    unit_id: 1540,
    opening_date: "2023-03-29",
    unit: {
      id: 1540,
      name: "Verb to be",
      points: 131,
      coins: 131,
      order: 1,
      system_order: 101,
      level: {
        id: 2,
        name: "Elementary",
      },
      parent_unit: {
        id: 1530,
        name: "Unit 1",
        points: 0,
        coins: 0,
        order: 1,
        system_order: 100,
        level: {
          id: 2,
          name: "Elementary",
        },
      },
    },
    student_unit: {
      passed: 0,
      opened: 1,
      unit_id: 1540,
      is_populated: 0,
      collected_points: 0,
      total_points: 0,
      collected_coins: 0,
      total_coins: 0,
      user_id: 103977,
    },
    student_units: [],
  },
  {
    id: 146602,
    opened: 1,
    unit_id: 1540,
    opening_date: "2023-03-29",
    unit: {
      id: 1540,
      name: "Verb to be",
      points: 131,
      coins: 131,
      order: 1,
      system_order: 101,
      level: {
        id: 2,
        name: "Elementary",
      },
      parent_unit: {
        id: 1530,
        name: "Unit 1",
        points: 0,
        coins: 0,
        order: 1,
        system_order: 100,
        level: {
          id: 2,
          name: "Elementary",
        },
      },
    },
    student_unit: {
      passed: 0,
      opened: 1,
      unit_id: 1540,
      is_populated: 0,
      collected_points: 0,
      total_points: 0,
      collected_coins: 0,
      total_coins: 0,
      user_id: 103977,
    },
    student_units: [],
  },
];
