import React from "react";
import { AbsMergedWithUnit as AbsMergedWithUnitComp } from "components";

const AbsMergedWithUnit = () => {
  const data = {
    id: 272364,
    status: 300,
    user_id: 146666,
    group_id: 4253,
    start_date: "2024-03-04",
    added_date: "2024-03-01 00:00:00",
    finish_date: null,
    deleted_at: null,
    student_next_status: null,
    leaving_category_id: null,
    leaving_reason: null,
    added_by: null,
    isRedList: true,
    isBlackList: true,
    user: {
      id: 146666,
      username: "a.ikromov9",
      email: "a.ikromov9@gmail.com",
      status: 100,
      created_at: "2024-02-26 18:23:13",
      updated_at: "2024-03-18 10:19:44",
      userProfile: {
        user_id: 146666,
        firstname: "Abduaziz",
        middlename: null,
        lastname: "Ikromov",
        locale: "uz-UZ",
        gender: 1,
        description: null,
        bio: null,
        dob: "2000-03-23",
        avatar: {
          full_url:
            "https://d38pzfvpoaatp4.cloudfront.net/2/9_YCLrsPSh_tR3Un90oHHEqWhR2nSUTz.png",
          base_url: "https://d38pzfvpoaatp4.cloudfront.net",
          path: "2/9_YCLrsPSh_tR3Un90oHHEqWhR2nSUTz.png",
          id: 518940,
          children: [
            {
              full_url:
                "https://d38pzfvpoaatp4.cloudfront.net/optimized-images/nZ0oSpVAryI30_kszUbj-4zQT4aJ-tARFSdr4j3IkNfgkkhaQgT8SIlZsq6-9DtC-small.webp",
              base_url: "https://d38pzfvpoaatp4.cloudfront.net",
              path: "optimized-images/nZ0oSpVAryI30_kszUbj-4zQT4aJ-tARFSdr4j3IkNfgkkhaQgT8SIlZsq6-9DtC-small.webp",
              resolution: "small",
            },
            {
              full_url:
                "https://d38pzfvpoaatp4.cloudfront.net/optimized-images/AaZpd_ybRcEf_NTAH1cn0_NUbm-dotJVElbTyfxs8FvxU3qyOZn_Wnkl8LgyZZN7-thumb.webp",
              base_url: "https://d38pzfvpoaatp4.cloudfront.net",
              path: "optimized-images/AaZpd_ybRcEf_NTAH1cn0_NUbm-dotJVElbTyfxs8FvxU3qyOZn_Wnkl8LgyZZN7-thumb.webp",
              resolution: "thumb",
            },
          ],
        },
        age: 24,
      },
      balance: null,
      student: {
        user_id: 146666,
        note: "Done! Will study told to azizkhon 04.04",
        status: 200,
        type: 200,
        branch_id: 9,
        source_id: 33,
        updated_at: "2024-03-01 11:11:21",
        isBlackList: true,
        permissionLabels: {
          start_date: false,
          coming: false,
          will_pay: true,
          checked: false,
          dont_take_mot: true,
          call_request: false,
          not_answered: true,
          podo: true,
          colour_change: false,
          lifecycle: true,
        },
      },
      userLabels: [
        {
          id: 619018,
          type: 800,
          datetime: null,
          note: null,
          color: null,
          user: {
            id: 146666,
            username: "a.ikromov9",
            email: "a.ikromov9@gmail.com",
            status: 100,
            created_at: "2024-02-26 18:23:13",
            updated_at: "2024-03-18 10:19:44",
            userProfile: {
              user_id: 146666,
              firstname: "Abduaziz",
              middlename: null,
              lastname: "Ikromov",
              locale: "uz-UZ",
              gender: 1,
              description: null,
              bio: null,
              dob: "2000-03-23",
            },
            balance: null,
          },
          left_units_count: 3,
          createdBy: null,
        },
        {
          id: 633916,
          type: 300,
          datetime: "2024-04-05 00:00:00",
          note: null,
          color: null,
          user: {
            id: 146666,
            username: "a.ikromov9",
            email: "a.ikromov9@gmail.com",
            status: 100,
            created_at: "2024-02-26 18:23:13",
            updated_at: "2024-03-18 10:19:44",
            userProfile: {
              user_id: 146666,
              firstname: "Abduaziz",
              middlename: null,
              lastname: "Ikromov",
              locale: "uz-UZ",
              gender: 1,
              description: null,
              bio: null,
              dob: "2000-03-23",
            },
            balance: null,
          },
          left_units_count: null,
          createdBy: {
            id: 111158,
            username: "a.gulsina",
            email: "a@gmail.com",
            status: 100,
            created_at: "2023-04-05 21:57:06",
            updated_at: "2024-04-05 08:26:34",
            userProfile: {
              user_id: 111158,
              firstname: "Gulsina",
              middlename: null,
              lastname: "Abdullova",
              locale: "ru-RU",
              gender: 0,
              description: null,
              bio: null,
              dob: "1995-04-18",
            },
            balance: null,
          },
        },
        {
          id: 635200,
          type: 600,
          datetime: "2024-04-05 11:33:08",
          note: "is not responding to phone calls \nunreacahable student\nskips many callses",
          color: null,
          user: {
            id: 146666,
            username: "a.ikromov9",
            email: "a.ikromov9@gmail.com",
            status: 100,
            created_at: "2024-02-26 18:23:13",
            updated_at: "2024-03-18 10:19:44",
            userProfile: {
              user_id: 146666,
              firstname: "Abduaziz",
              middlename: null,
              lastname: "Ikromov",
              locale: "uz-UZ",
              gender: 1,
              description: null,
              bio: null,
              dob: "2000-03-23",
            },
            balance: null,
          },
          left_units_count: null,
          createdBy: {
            id: 104954,
            username: "k.marvarid",
            email: "a@gmail.com",
            status: 100,
            created_at: "2023-02-09 12:46:23",
            updated_at: "2024-04-05 13:28:11",
            userProfile: {
              user_id: 104954,
              firstname: "Marvarid",
              middlename: null,
              lastname: "Komilova",
              locale: "ru-RU",
              gender: 0,
              description: null,
              bio: null,
              dob: "2001-08-07",
            },
            balance: null,
          },
        },
      ],
      userPhones: [
        {
          id: 87664,
          type: 100,
          phone_number: "998990222418",
          is_confirmed: 1,
        },
        {
          id: 87665,
          type: 600,
          phone_number: "998770100327",
          is_confirmed: 0,
        },
      ],
    },
    actualPayment: {
      id: 214003,
      start_date: "2024-04-01",
      finish_date: "2024-04-29",
      debt: "888000.00",
      balance: "0.00",
      status: 300,
      lesson_count: 12,
      absence_count: 3,
      virtual: false,
      group_contact_id: 272364,
      year: "2024",
      month: "04",
      deleted_at: null,
    },
    contactResponsibles: [
      {
        id: 137190,
        type: 100,
        user: {
          id: 113700,
          username: "t.zarnigor",
          email: "a@gmail.com",
          status: 100,
          created_at: "2023-05-03 12:42:49",
          updated_at: "2024-04-05 07:46:27",
          userProfile: {
            user_id: 113700,
            firstname: "Zarnigor",
            middlename: null,
            lastname: "Tolibjonova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "2004-11-05",
          },
          balance: null,
        },
        contact_id: 272364,
        user_id: 113700,
        datetime: "2024-03-01 12:41:08",
      },
    ],
    group: {
      id: 4253,
      status: 100,
      state: 300,
      note: "",
      start_date: "2024-03-01",
      finish_date: "2024-05-31",
      version_id: 28192,
      lesson_time_id: 3,
      lesson_day_id: 1,
      group_type_id: 1,
      level_id: 9,
      name: "ENG 1235",
      created_at: "2024-02-16 13:41:53",
      updated_at: "2024-04-04 18:34:18",
      closing_reason: null,
      group_share: null,
      groupMentors: [
        {
          id: 34754,
          type: 100,
          user_id: 131374,
          version_id: 34754,
          user: {
            id: 131374,
            username: "n.gulkhayo",
            email: "n.gulkhayogmail.com",
            status: 100,
            created_at: "2023-09-14 15:03:10",
            updated_at: "2024-04-05 07:30:54",
            userProfile: {
              user_id: 131374,
              firstname: "Gulkhayo",
              middlename: null,
              lastname: "Normukhamedova",
              locale: "en-US",
              gender: 0,
              description: null,
              bio: null,
              dob: "1997-09-02",
            },
            balance: null,
          },
        },
        {
          id: 34755,
          type: 200,
          user_id: 104954,
          version_id: 34755,
          user: {
            id: 104954,
            username: "k.marvarid",
            email: "a@gmail.com",
            status: 100,
            created_at: "2023-02-09 12:46:23",
            updated_at: "2024-04-05 13:28:11",
            userProfile: {
              user_id: 104954,
              firstname: "Marvarid",
              middlename: null,
              lastname: "Komilova",
              locale: "ru-RU",
              gender: 0,
              description: null,
              bio: null,
              dob: "2001-08-07",
            },
            balance: null,
          },
        },
      ],
      level: {
        id: 9,
        order: 120000,
        name: "Middle",
        duration: 2592000,
        parent_id: 1,
        data: {
          has_exam: true,
          should_assign_units: true,
          calculate_unit_progress: true,
        },
        parent: {
          id: 1,
          order: 100000,
          name: "Beginner",
          duration: 7776000,
          parent_id: null,
          data: {
            has_exam: true,
            should_assign_units: true,
            calculate_unit_progress: true,
          },
        },
      },
      groupType: {
        id: 1,
        name: "Groups ",
        min_age: 13,
        max_age: 30,
        min_count: 14,
        max_count: 14,
        additional_seat: 4,
        color: null,
        group_form: 200,
        status: 100,
        lesson_duration: 4800,
      },
      lessonDay: {
        id: 1,
        name: "Odd days",
        status: 100,
      },
      lessonTime: {
        id: 3,
        time: "10:30:00",
        duration: null,
      },
      room: {
        id: 258,
        name: "X Room-18",
        capacity: null,
        status: 100,
        type: 100,
        branch: {
          id: 9,
          name: "Xalqlar Do’stligi",
          address: null,
          landmark: null,
          latitude: null,
          longitude: null,
          description: null,
          location_url: null,
          status: 100,
          region_id: 1,
          deleted_at: null,
        },
      },
    },
    permissionActions: {
      can_work_balance: false,
      can_stop: true,
    },
    buttonActions: {
      attend: false,
      transfer: true,
      transfer_back: false,
      stop: true,
      activate: false,
      delete: false,
      account_block: true,
      account_unblock: false,
      recommendation: false,
      back_to_waiting_list: false,
      attend_back: false,
      call: true,
      sms: true,
      can_single_pass: true,
      can_register_ielts_practicum: true,
      can_change_start_date: false,
    },
    student: {
      user_id: 146666,
      note: "Done! Will study told to azizkhon 04.04",
      status: 200,
      type: 200,
      branch_id: 9,
      source_id: 33,
      updated_at: "2024-03-01 11:11:21",
      isBlackList: true,
    },
    abs_count: "3",
    absDates: [
      {
        status: "300",
        date: "2024-04-01",
        id: "2079903",
        reason: "family issues",
      },
      {
        status: "300",
        date: "2024-04-03",
        id: "2095320",
        reason: "sick ",
      },
      {
        status: "300",
        date: "2024-04-05",
        id: "2110328",
        reason: "unknown",
      },
    ],
  };
  return (
    <div>
      <AbsMergedWithUnitComp original={data as any} />
    </div>
  );
};

export default AbsMergedWithUnit;
