import {
  TAB_ARCHIVED,
  TAB_NEW_STUDENT_ATTENDED,
  TAB_NEW_STUDENT_NOT_ATTENDED,
  TAB_STOPPING,
  TAB_STUDYING,
  TAB_TRANSFERRING,
  TAB_WAITING,
} from "constants/studentBalance";

export const tableCols = {
  [TAB_WAITING]: {
    name: true,
    phone: true,
    course: true,
    level: true,
    dayAndTime: true,
    branch: true,
    balance: true,
    note: true,
    date: true,
    actions: true,
  },
  [TAB_STUDYING]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_NEW_STUDENT_NOT_ATTENDED]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_NEW_STUDENT_ATTENDED]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_NEW_STUDENT_NOT_ATTENDED]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_TRANSFERRING]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_STOPPING]: {
    name: true,
    phone: true,
    periods: true,
    countLesson: true,
    balance: true,
    note: true,
    groupInfo: true,
    actions: true,
  },
  [TAB_ARCHIVED]: {
    name: true,
    phone: true,
    stoppedCategory: true,
    balance: true,
    note: true,
    actions: true,
  },
};
