import { ETabStatuses } from "types";

export const tab_fields = {
  [ETabStatuses.TAB_WAITING]: {
    name: true,
    phone: true,
    course: true,
    level: true,
    day_time: true,
    branch: true,
    note: true,
    date: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_NEW_STUDENT_NOT_ATTENDED]: {
    name: true,
    phone: true,
    period: true,
    lesson: true,
    payment: true,
    group_info: true,
    note: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_NEW_STUDENT_ATTENDED]: {
    name: true,
    phone: true,
    period: true,
    lesson: true,
    payment: true,
    group_info: true,
    note: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_STUDYING]: {
    name: true,
    phone: true,
    period: true,
    lesson: true,
    payment: true,
    group_info: true,
    note: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_TRANSFERRING]: {
    name: true,
    phone: true,
    period: true,
    lesson: true,
    payment: true,
    group_info: true,
    note: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_STOPPING]: {
    name: true,
    phone: true,
    period: true,
    lesson: true,
    payment: true,
    group_info: true,
    note: true,
    label: true,
    action: true,
  },
  [ETabStatuses.TAB_ARCHIVED]: {
    name: true,
    phone: true,
    last_group_info: true,
    stoppedCategory: true,
    note: true,
    archivedDate: true,
    label: true,
    action: true,
  },
};
