import React from "react";
import { GroupInterface as GroupInterfaceComponent } from "components";

const GroupInterface = () => {
  const data = {
    id: 3912,
    status: 100,
    state: 300,
    note: "Bekzod Turdibekov 999873538 05.01",
    start_date: "2023-12-01",
    finish_date: "2024-02-29",
    version_id: 25883,
    lesson_time_id: 6,
    lesson_day_id: 1,
    group_type_id: 1,
    level_id: 10,
    name: "ENG 781",
    created_at: "2023-11-18 10:20:14",
    updated_at: "2023-12-01 15:50:22",
    closing_reason: null,
    group_share: null,
    buttonActions: {
      edit: true,
      delete: false,
      take: true,
      sms: true,
      create: true,
      changeTeacher: true,
    },
    groupMentors: [
      {
        id: 31165,
        type: 100,
        user_id: 46,
        version_id: 31165,
        user: {
          id: 46,
          username: "b.alibaev",
          email: "a@gmail.com",
          status: 100,
          created_at: "2018-04-21 13:03:06",
          updated_at: "2024-02-22 11:27:11",
          userProfile: {
            user_id: 46,
            firstname: "Bekmurod",
            middlename: null,
            lastname: "Alibaev",
            locale: "ru-RU",
            gender: 1,
            description: null,
            bio: null,
            dob: "1992-05-17",
          },
          balance: null,
          staff: {
            user_id: 46,
            key: 100,
            status: 200,
            datetime: "2023-04-17 14:38:59",
            hired_date: "2018-10-01 00:00:00",
            next_recommended_vacation: "2019-10",
            nation_id: 1,
            family_status: 100,
            job_type: 100,
            passport_number: "AB9651497",
            citizenship: "uzbekistan",
            passport_given_date: "2018-05-20",
            passport_expire_date: "2028-05-19",
            passport_given_by: "Toshkent viloyati, Quyichirchiq tumani IIB ",
            born_address: "tashkent_province",
            official_address:
              "Toshkent shahri, Sergeli Tumani  3, Nurhayot mfy, 30/11",
            live_address:
              "Toshkent viloyati, Quyichirchiq tumani, Galabotir mfy, Istiqlol kochasi, 1-uy",
            ielts_score: 0,
            candidate_id: 2353,
          },
        },
      },
      {
        id: 31166,
        type: 200,
        user_id: 100538,
        version_id: 31166,
        user: {
          id: 100538,
          username: "a.fozila",
          email: "a@gmail.com",
          status: 100,
          created_at: "2023-01-09 11:48:29",
          updated_at: "2024-04-02 07:09:30",
          userProfile: {
            user_id: 100538,
            firstname: "Fozila",
            middlename: null,
            lastname: "Akbarova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "2002-03-13",
          },
          balance: null,
          staff: {
            user_id: 100538,
            key: 600,
            status: 200,
            datetime: "2023-04-11 17:01:26",
            hired_date: "2023-01-09 11:43:12",
            next_recommended_vacation: "2025-01",
            nation_id: 1,
            family_status: 200,
            job_type: 200,
            passport_number: "AB9283444",
            citizenship: "uzbekistan",
            passport_given_date: "2018-04-10",
            passport_expire_date: "2028-04-09",
            passport_given_by: "Tashkent shahar Olmazor tumani IIB ",
            born_address: "tashkent",
            official_address: "Tashkent shahar, Olamzor tumani, Farobiy 5/15",
            live_address:
              "Tashkent shahar, Olamzor tumani, Farobiy kuchasi 5/15",
            ielts_score: 6.5,
            candidate_id: 16668,
          },
        },
      },
    ],
    course: {
      id: 1,
      name: "English",
      status: 100,
    },
    level: {
      id: 10,
      order: 130000,
      name: "Final",
      duration: 2592000,
      parent_id: 1,
      data: {
        has_exam: true,
        should_assign_units: true,
        calculate_unit_progress: true,
      },
      parent: {
        id: 1,
        order: 100000,
        name: "Beginner",
        duration: 7776000,
        parent_id: null,
        data: {
          has_exam: true,
          should_assign_units: true,
          calculate_unit_progress: true,
        },
      },
    },
    groupType: {
      id: 1,
      name: "Groups ",
      min_age: 13,
      max_age: 30,
      min_count: 14,
      max_count: 14,
      additional_seat: 4,
      color: null,
      group_form: 200,
      status: 100,
      lesson_duration: 4800,
    },
    lessonDay: {
      id: 1,
      name: "Odd days",
      status: 100,
    },
    lessonTime: {
      id: 6,
      time: "15:30:00",
      duration: null,
    },
    room: {
      id: 215,
      name: "X Room-27",
      capacity: null,
      status: 100,
      type: 100,
      branch: {
        id: 9,
        name: "Xalqlar Do’stligi",
        address: null,
        landmark: null,
        latitude: null,
        longitude: null,
        description: null,
        location_url: null,
        status: 100,
        region_id: 1,
        deleted_at: null,
      },
    },
    total_study_contact_count: "15",
    real_total_contact_count: "15",
    new_student_not_attended_contact_count: "0",
    new_student_attended_contact_count: "0",
    free_place: 0,
    payment_count: "0",
    partial_payed_count: "0",
    responsible: null,
  };
  return (
    <div>
      <GroupInterfaceComponent group={data as any} />
    </div>
  );
};

export default GroupInterface;
