import React from "react";
import { AntdInfoCell as AntdInfoCellComp } from "components";

const AntdInfoCell = () => {
  const value = {
    id: 3493,
    status: 100,
    state: 300,
    note: null,
    start_date: "2023-09-15",
    finish_date: "2023-11-30",
    version_id: 25598,
    lesson_time_id: 2,
    lesson_day_id: 1,
    group_type_id: 1,
    level_id: 13,
    name: "ENG 704",
    created_at: "2023-08-29 16:17:39",
    updated_at: "2023-09-20 15:10:52",
    closing_reason: null,
    group_share: null,
    groupMentors: [
      {
        id: 30541,
        type: 100,
        user_id: 28225,
        version_id: 30541,
        user: {
          id: 28225,
          username: "z.nazarova",
          email: "a@gmail.com",
          status: 100,
          created_at: "2020-11-30 11:48:56",
          updated_at: "2024-03-06 11:17:39",
          userProfile: {
            user_id: 28225,
            firstname: "Ziyoda",
            middlename: null,
            lastname: "Nazarova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "1984-07-22",
          },
          balance: null,
        },
      },
      {
        id: 30542,
        type: 200,
        user_id: 75612,
        version_id: 30542,
        user: {
          id: 75612,
          username: "s",
          email: "a@gmail.com",
          status: 100,
          created_at: "2022-06-10 17:42:56",
          updated_at: "2024-03-25 08:55:04",
          userProfile: {
            user_id: 75612,
            firstname: "Shaxnoza",
            middlename: null,
            lastname: "Temirbekova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "1999-06-28",
          },
          balance: null,
        },
      },
    ],
    level: {
      id: 13,
      order: 230000,
      name: "Final",
      duration: 2592000,
      parent_id: 2,
      data: {
        has_exam: true,
        should_assign_units: true,
        calculate_unit_progress: true,
      },
      parent: {
        id: 2,
        order: 200000,
        name: "Elementary",
        duration: 7776000,
        parent_id: null,
        data: {
          has_exam: true,
          should_assign_units: true,
          calculate_unit_progress: true,
        },
      },
    },
    groupType: {
      id: 1,
      name: "Groups ",
      min_age: 13,
      max_age: 30,
      min_count: 14,
      max_count: 14,
      additional_seat: 4,
      color: null,
      group_form: 200,
      status: 100,
      lesson_duration: 4800,
    },
    lessonDay: {
      id: 1,
      name: "Odd days",
      status: 100,
      lessonWeekDayIndexes: ["1", "3", "5"],
    },
    lessonDays: [
      "2024-04-01",
      "2024-04-03",
      "2024-04-05",
      "2024-04-08",
      "2024-04-10",
      "2024-04-12",
      "2024-04-15",
      "2024-04-17",
      "2024-04-19",
      "2024-04-22",
      "2024-04-24",
      "2024-04-26",
      "2024-04-29",
    ],
    lessonTime: {
      id: 2,
      time: "09:00:00",
      duration: null,
    },
    room: {
      id: 193,
      name: "Yu Room 1",
      capacity: null,
      status: 100,
      type: 100,
      branch: {
        id: 8,
        name: "Yunusobod",
        address:
          "Узбекистан, Ташкент, Юнусабадский район, Ц-6, ул. Амир Темур шох, дом 86 А, Tashkent 100084",
        landmark: "Metro Minor",
        latitude: null,
        longitude: null,
        description: null,
        location_url: "https://goo.gl/maps/HqoWayd9EFUXqSPk6",
        status: 100,
        region_id: 1,
        deleted_at: null,
      },
    },
    teacher: {
      id: 30541,
      type: 100,
      user_id: 28225,
      version_id: 30541,
      user: {
        id: 28225,
        username: "z.nazarova",
        email: "a@gmail.com",
        status: 100,
        created_at: "2020-11-30 11:48:56",
        updated_at: "2024-03-06 11:17:39",
        userProfile: {
          user_id: 28225,
          firstname: "Ziyoda",
          middlename: null,
          lastname: "Nazarova",
          locale: "ru-RU",
          gender: 0,
          description: null,
          bio: null,
          dob: "1984-07-22",
        },
        balance: null,
      },
    },
    support: {
      id: 30542,
      type: 200,
      user_id: 75612,
      version_id: 30542,
      user: {
        id: 75612,
        username: "s",
        email: "a@gmail.com",
        status: 100,
        created_at: "2022-06-10 17:42:56",
        updated_at: "2024-03-25 08:55:04",
        userProfile: {
          user_id: 75612,
          firstname: "Shaxnoza",
          middlename: null,
          lastname: "Temirbekova",
          locale: "ru-RU",
          gender: 0,
          description: null,
          bio: null,
          dob: "1999-06-28",
        },
        balance: null,
      },
    },
  };
  const record = {
    id: 231734,
    status: 300,
    user: {
      id: 132231,
      username: "s.tokhtamatov",
      email: "s.tokhtamatov@gmail.com",
      status: 100,
      created_at: "2023-09-20 10:46:36",
      updated_at: "2024-02-23 09:05:15",
      userProfile: {
        user_id: 132231,
        firstname: "Sarvar",
        middlename: null,
        lastname: "Tokhtamatov",
        locale: "uz-UZ",
        gender: 1,
        description: "DONE WILL STUDY told m.mokhira 22.01 ",
        bio: null,
        dob: "2006-03-09",
        avatar: {
          full_url:
            "https://d38pzfvpoaatp4.cloudfront.net/2/MMXWqXewfzMHyz_7ovQYU3NqqsiSnMox.png",
          base_url: "https://d38pzfvpoaatp4.cloudfront.net",
          path: "2/MMXWqXewfzMHyz_7ovQYU3NqqsiSnMox.png",
          id: 478213,
          children: [
            {
              full_url:
                "https://d38pzfvpoaatp4.cloudfront.net/optimized-images/pVxLqpgr_JQ0JkQVyk0qipPvBXGOT4JFhak3I_Ba-IDNMnPHIR2kKGMMxaOGFhsR-medium.webp",
              base_url: "https://d38pzfvpoaatp4.cloudfront.net",
              path: "optimized-images/pVxLqpgr_JQ0JkQVyk0qipPvBXGOT4JFhak3I_Ba-IDNMnPHIR2kKGMMxaOGFhsR-medium.webp",
              resolution: "medium",
            },
            {
              full_url:
                "https://d38pzfvpoaatp4.cloudfront.net/optimized-images/s-RuYE0Ddbv5KOFgz9TM1aXU_HRPnNwyeVfopyNNyTqqt2yWh9KWvgXPoDOUEg_G-small.webp",
              base_url: "https://d38pzfvpoaatp4.cloudfront.net",
              path: "optimized-images/s-RuYE0Ddbv5KOFgz9TM1aXU_HRPnNwyeVfopyNNyTqqt2yWh9KWvgXPoDOUEg_G-small.webp",
              resolution: "small",
            },
            {
              full_url:
                "https://d38pzfvpoaatp4.cloudfront.net/optimized-images/d7E6LGsoivHQRINr6hTjfB4A_5GHOGLGEy9KAArcOLIlJeX4pdBk6eJ2grfGys3q-thumb.webp",
              base_url: "https://d38pzfvpoaatp4.cloudfront.net",
              path: "optimized-images/d7E6LGsoivHQRINr6hTjfB4A_5GHOGLGEy9KAArcOLIlJeX4pdBk6eJ2grfGys3q-thumb.webp",
              resolution: "thumb",
            },
          ],
        },
      },
      balance: null,
      student: {
        user_id: 132231,
        note: "done willl study told A.Madina 15.02//pay on today 09.02told Jasur ||DONE WILL STUDY told m.mokhira 22.01 ",
        status: 200,
        type: 200,
        branch_id: 8,
        source_id: 40,
        updated_at: "2023-09-20 10:46:36",
        isBlackList: true,
        permissionLabels: {
          start_date: false,
          coming: false,
          will_pay: true,
          checked: false,
          dont_take_mot: true,
          call_request: false,
          not_answered: true,
          podo: true,
          colour_change: false,
          lifecycle: true,
        },
      },
      userLabels: [
        {
          id: 540553,
          type: 500,
          datetime: "2024-04-03 12:22:38",
          note: null,
          color: null,
          user: {
            id: 132231,
            username: "s.tokhtamatov",
            email: "s.tokhtamatov@gmail.com",
            status: 100,
            created_at: "2023-09-20 10:46:36",
            updated_at: "2024-02-23 09:05:15",
            userProfile: {
              user_id: 132231,
              firstname: "Sarvar",
              middlename: null,
              lastname: "Tokhtamatov",
              locale: "uz-UZ",
              gender: 1,
              description: "DONE WILL STUDY told m.mokhira 22.01 ",
              bio: null,
              dob: "2006-03-09",
            },
            balance: null,
          },
          left_units_count: null,
          createdBy: null,
        },
      ],
      userPhones: [
        {
          id: 72857,
          type: 100,
          phone_number: "998881863305",
          is_confirmed: 1,
        },
        {
          id: 57138,
          type: 600,
          phone_number: "998997252379",
          is_confirmed: 0,
        },
        {
          id: 57139,
          type: 600,
          phone_number: "998946953305",
          is_confirmed: 0,
        },
        {
          id: 84610,
          type: 600,
          phone_number: "998900333103",
          is_confirmed: 0,
        },
      ],
    },
    start_date: "2023-09-22",
    added_date: "2023-09-22 00:00:00",
    finish_date: null,
    deleted_at: null,
    actualPayment: {
      id: 199542,
      start_date: "2024-04-01",
      finish_date: "2024-04-29",
      debt: "888000.00",
      balance: "0.00",
      status: 300,
      lesson_count: 12,
      absence_count: null,
      virtual: false,
      group_contact_id: 231734,
      year: "2024",
      month: "04",
      deleted_at: null,
    },
    group_id: 3493,
    contactResponsibles: [
      {
        id: 67717,
        type: 100,
        user: {
          id: 85331,
          username: "d.zebo",
          email: "a@gmail.com",
          status: 300,
          created_at: "2022-09-08 19:21:31",
          updated_at: "2023-11-18 13:29:43",
          userProfile: {
            user_id: 85331,
            firstname: "Zebo",
            middlename: null,
            lastname: "Dosmetova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "2000-07-18",
          },
          balance: null,
        },
        contact_id: 231734,
        user_id: 85331,
        datetime: "2023-09-20 10:46:53",
      },
    ],
    student_next_status: null,
    isRedList: false,
    isBlackList: true,
    is_progress: 0,
    group: {
      id: 3493,
      status: 100,
      state: 300,
      note: null,
      start_date: "2023-09-15",
      finish_date: "2023-11-30",
      version_id: 25598,
      lesson_time_id: 2,
      lesson_day_id: 1,
      group_type_id: 1,
      level_id: 13,
      name: "ENG 704",
      created_at: "2023-08-29 16:17:39",
      updated_at: "2023-09-20 15:10:52",
      closing_reason: null,
      group_share: null,
      groupMentors: [
        {
          id: 30541,
          type: 100,
          user_id: 28225,
          version_id: 30541,
          user: {
            id: 28225,
            username: "z.nazarova",
            email: "a@gmail.com",
            status: 100,
            created_at: "2020-11-30 11:48:56",
            updated_at: "2024-03-06 11:17:39",
            userProfile: {
              user_id: 28225,
              firstname: "Ziyoda",
              middlename: null,
              lastname: "Nazarova",
              locale: "ru-RU",
              gender: 0,
              description: null,
              bio: null,
              dob: "1984-07-22",
            },
            balance: null,
          },
        },
        {
          id: 30542,
          type: 200,
          user_id: 75612,
          version_id: 30542,
          user: {
            id: 75612,
            username: "s",
            email: "a@gmail.com",
            status: 100,
            created_at: "2022-06-10 17:42:56",
            updated_at: "2024-03-25 08:55:04",
            userProfile: {
              user_id: 75612,
              firstname: "Shaxnoza",
              middlename: null,
              lastname: "Temirbekova",
              locale: "ru-RU",
              gender: 0,
              description: null,
              bio: null,
              dob: "1999-06-28",
            },
            balance: null,
          },
        },
      ],
      level: {
        id: 13,
        order: 230000,
        name: "Final",
        duration: 2592000,
        parent_id: 2,
        data: {
          has_exam: true,
          should_assign_units: true,
          calculate_unit_progress: true,
        },
        parent: {
          id: 2,
          order: 200000,
          name: "Elementary",
          duration: 7776000,
          parent_id: null,
          data: {
            has_exam: true,
            should_assign_units: true,
            calculate_unit_progress: true,
          },
        },
      },
      groupType: {
        id: 1,
        name: "Groups ",
        min_age: 13,
        max_age: 30,
        min_count: 14,
        max_count: 14,
        additional_seat: 4,
        color: null,
        group_form: 200,
        status: 100,
        lesson_duration: 4800,
      },
      lessonDay: {
        id: 1,
        name: "Odd days",
        status: 100,
        lessonWeekDayIndexes: ["1", "3", "5"],
      },
      lessonDays: [
        "2024-04-01",
        "2024-04-03",
        "2024-04-05",
        "2024-04-08",
        "2024-04-10",
        "2024-04-12",
        "2024-04-15",
        "2024-04-17",
        "2024-04-19",
        "2024-04-22",
        "2024-04-24",
        "2024-04-26",
        "2024-04-29",
      ],
      lessonTime: {
        id: 2,
        time: "09:00:00",
        duration: null,
      },
      room: {
        id: 193,
        name: "Yu Room 1",
        capacity: null,
        status: 100,
        type: 100,
        branch: {
          id: 8,
          name: "Yunusobod",
          address:
            "Узбекистан, Ташкент, Юнусабадский район, Ц-6, ул. Амир Темур шох, дом 86 А, Tashkent 100084",
          landmark: "Metro Minor",
          latitude: null,
          longitude: null,
          description: null,
          location_url: "https://goo.gl/maps/HqoWayd9EFUXqSPk6",
          status: 100,
          region_id: 1,
          deleted_at: null,
        },
      },
      teacher: {
        id: 30541,
        type: 100,
        user_id: 28225,
        version_id: 30541,
        user: {
          id: 28225,
          username: "z.nazarova",
          email: "a@gmail.com",
          status: 100,
          created_at: "2020-11-30 11:48:56",
          updated_at: "2024-03-06 11:17:39",
          userProfile: {
            user_id: 28225,
            firstname: "Ziyoda",
            middlename: null,
            lastname: "Nazarova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "1984-07-22",
          },
          balance: null,
        },
      },
      support: {
        id: 30542,
        type: 200,
        user_id: 75612,
        version_id: 30542,
        user: {
          id: 75612,
          username: "s",
          email: "a@gmail.com",
          status: 100,
          created_at: "2022-06-10 17:42:56",
          updated_at: "2024-03-25 08:55:04",
          userProfile: {
            user_id: 75612,
            firstname: "Shaxnoza",
            middlename: null,
            lastname: "Temirbekova",
            locale: "ru-RU",
            gender: 0,
            description: null,
            bio: null,
            dob: "1999-06-28",
          },
          balance: null,
        },
      },
    },
    actualTransfers: [],
    permissionActions: {
      can_work_balance: false,
      can_stop: false,
    },
    buttonActions: {
      attend: false,
      transfer: true,
      transfer_back: false,
      stop: true,
      activate: false,
      delete: false,
      account_block: true,
      account_unblock: false,
      recommendation: false,
      back_to_waiting_list: false,
      attend_back: false,
      call: true,
      sms: true,
      can_single_pass: true,
      can_register_ielts_practicum: true,
      can_change_start_date: true,
    },
  };
  return (
    <div>
      <AntdInfoCellComp value={value} record={record} />
    </div>
  );
};

export default AntdInfoCell;
