import {
  admin_finance_stationary_cancel,
  admin_student_recommended_groups,
} from "../../hooks";

export const queryKeys = {
  admin_finance_salary_detailed_salary_group:
    "admin_finance_salary_detailed_salary_group",
  admin_finance_salary_last_months: "admin_finance_salary_last_months",
  admin_level_config_get_mock_config: "admin_level_config_get_mock_config",
  admin_finance_referral_form_page_data:
    "admin_finance_referral_form_page_data",
  admin_ranking_observation_index: "admin_ranking_observation_index",
  admin_student_list: "admin_student_list",
  admin_statistics_call_index: "admin_statistics_call_index",
  admin_referral_index: "admin_referral_index",
  admin_referral_page_data: "admin_referral_page_data",
  admin_referral_statistics: "admin_referral_statistics",
  admin_get_call_template_page_data: "admin_get_call_template_page_data",
  admin_shop_statistics: "admin_shop_statistics",
  admin_finance_salary_view: "admin_finance_salary_view",
  get_waiting_list_config: "get_waiting_list_config",
  admin_support_daily_office_hours: "admin_support_daily_office_hours",
  admin_academic_podo_requests: "admin_academic_podo_requests",
  admin_academic_podo_request: "admin_academic_podo_request",
  admin_statistics_podo_request: "admin_statistics_podo_request",
  admin_academic_potential_fail_requests:
    "admin_academic_potential_fail_requests",
  admin_get_sms_service: "admin_get_sms_service",
  admin_student_recommended_groups: "admin_student_recommended_groups",
  admin_academic_podo_request_reviewer_groups:
    "admin_academic_podo_request_reviewer_groups",
  admin_academic_potential_fail_request:
    "admin_academic_potential_fail_request",
  admin_ranking_observation_view: "admin_ranking_observation_view",
  admin_academic_potential_fail_request_reviewer_groups:
    "admin_academic_potential_fail_request_reviewer_groups",
  admin_ranking_observation_enums: "admin_ranking_observation_enums",
  admin_ranking_observation_statistics: "admin_ranking_observation_statistics",
  admin_ranking_observation_mentor_list:
    "admin_ranking_observation_mentor_list",
  admin_grouped_stop_calculation: "admin-grouped-stop-calculation",
  admin_client_staff: "admin-client-staff",
  student_order: "student-order",
  system_tax_device_index: "system_tax_device_index",
  get_vacation_slots: "get_vacation_slots",
  get_vacation_details_slots: "get_vacation_details_slots",
  get_user_vacation_details: "get_user_vacation_details",
  get_active_vacations: "get_active_vacations",
  get_vacation_details_one: "get_vacation_details_one",
  get_main_schedule_data: "get_main_schedule_data",
  get_assignment_view_vacation: "get_assignment_view_vacation",
  get_vacation_data_by_user: "get_vacation_data_by_user",
  student_progress: "student_progress",
  admin_product_view: "admin_product_view",
  admin_product_cashbox: "admin_product_cashbox",
  admin_product_index: "admin_product_index",
  admin_ranking_get_mentor_rank_config: "admin_ranking_get_mentor_rank_config",
  redList: "admin-grouped-group-contact-red-list",
  redListStatistics: "admin_academic_red_list_by_teacher",
  admin_grouped_group_contact_absent_student:
    "admin-grouped-group-contact-absent-student",
  system_student_homeworks: "system_student_homeworks",
  admin_order_index: "admin_order_index",
  admin_academic_fallible_get_by_group: "admin_academic_fallible_get_by_group",
  admin_page_data: "admin_page_data",
  homework_not_done_list: "homework_not_done_list",
  admin_category_index: "admin_category_index",
  admin_product_transaction_statistics: "admin_product_transaction_statistics",
  unit_status_info: "unit_status_info",
  admin_finance_cash_flow_differences: "admin_finance_cash_flow_differences",
  admin_finance_stationary_give: "admin_finance_stationary_give",
  admin_finance_stationary_cancel: "admin_finance_stationary_cancel",
  admin_product_actions: "admin_product_actions",
  group_contact_last_attendance: "group_contact_last_attendance",
  academicControlListKey: "admin-academic-home-work-not-done",
  admin_academic_fallible_get_by_mentor:
    "admin_academic_fallible_get_by_mentor",
  groups: "admin-academic-home-work-not-done-by-group",
  controlAttendance: "academic-control-attendance",
  admin_ranking_mentor_rank_index: "admin_ranking_mentor_rank_index",
  client_ranking_mentor_rank_view: "client_ranking_mentor_rank_view",
  admin_ranking_mentor_rank_progress_by_year:
    "admin_ranking_mentor_rank_progress_by_year",
  controlProgress: "academic-control-Progress",
  system_stats_academic_progress_by_mentor:
    "system_stats_academic_progress_by_mentor",
  admin_finance_product_and_service_statistics:
    "admin_finance_product_and_service_statistics",
  admin_grouped_stop_page_data: "admin-grouped-stop-page-data",
  teacher_get_group_days: "teacher-get-group-days",
  teacher_get_group_scores: "teacher-get-group-scores",
  group_student_progress: "group-student-progress",
  get_exam_dates: "get-exam-dates",
  assignment_list: "assignment-list",
  assignment_one: "assignment-one",
  admin_group_get_attendance: "admin-group-get-attendance",
  banned_student_list: "banned-student-list",
  admin_grouped_group_contact_black_list:
    "admin-grouped-group-contact-black-list",
  branches_list: "branches-list",
  branch_list: "branch-list",
  call_user_list: "call-user-list",
  call_user_history: "call-user-history",
  call_staff_list: "call-staff-list",
  cash_flow: "cash-flow",
  admin_category_create: "admin_category_create",
  admin_v1_finance_payment_config_online_payment_page_data:
    "admin_v1_finance_payment_config_online_payment_page_data",
  admin_cashflow_expense_index: "admin-cashflow-expense-index",
  check_data: "receipt-data",
  product_check_data: "product-receipt-data",
  company_files: "company-files",
  company_file: "company-file",
  admin_company_file_category: "admin_company_file_category",
  admin_course_index: "admin-course-index",
  admin_course_view: "admin-course-view",
  sms_cron: "sms-cron",
  exam_dates: "exam-dates",
  department_list: "department-list",
  admin_finance_debt_statistic: "admin_finance_debt_statistic",
  admin_rbac_department_view: "admin-rbac-department-view",
  exam_data: "exam-data",
  admin_mock_inside_group: "admin_mock_inside_group",
  admin_mock_groups: "admin_mock_groups",
  can_get_receipt: "can-get-receipt",
  group_exam_data: "group-exam-data",
  group_exam_students: "group-exam-students",
  group_exam_students_contacts: "group-exam-students-contacts",
  exam_counts: "exam-counts",
  admin_exam_info_get_average_teacher: "admin_exam_info_get_average_teacher",
  admin_mock_exam_info_get_average_teacher:
    "admin_mock_exam_info_get_average_teacher",
  v1_system_exam_exam_stats: "v1_system_exam_exam_stats",
  admin_mock_stats: "admin_mock_stats",
  admin_get_exam_user: "admin_get_exam_user",
  admin_mock_exam_get_average_by_teacher:
    "admin_mock_exam_get_average_by_teacher",
  sms_exclusion: "sms-exclusion",
  sms_exclusion_page_data: "sms-exclusion-page-data",
  sms_exclusion_one: "sms-exclusion-one",
  call_exclusion_one: "call-exclusion-one",
  admin_finance_expense_category_index: "admin-finance-expense-category-index",
  admin_finance_expense_index: "admin-finance-expense-index",
  admin_finance_product_and_service_enums:
    "admin-finance-product-and-service-enums",
  admin_finance_product_and_service_index:
    "admin-finance-product-and-service-index",
  admin_finance_product_and_service_view:
    "admin-finance-product-and-service-view",
  admin_finance_income_index: "admin-finance-orderTabs-index",
  admin_finance_income_view: "admin-finance-orderTabs-view",
  admin_finance_expense_view: "admin-finance-expense-view",
  admin_finance_statistic: "admin-finance-statistic",
  admin_finance_statistic_online_payment:
    "admin_finance_statistic_online_payment",
  admin_group_life_cycle: "admin_group_life_cycle",
  finance_config_page_data: "finance-config-page-data",
  admin_group_schedule_page: "admin-group-schedule-page",
  admin_group_statistic_by_students_count:
    "admin_group_statistic_by_students_count",
  admin_group_mentor_replace_info: "admin_group_mentor_replace_info",
  admin_group_schedule_data: "admin-group-schedule-data",
  admin_group_index: "admin-group-index",
  admin_group_view: "admin-group-view",
  admin_group_info: "admin-group-info",
  admin_group_initial_page: "admin-group-initial-page",
  admin_group_study_types: "admin-group-study-types",
  admin_staff_groups: "admin_staff_groups",
  admin_course_group_type_index: "admin-course-group-type-index",
  admin_course_group_type_view: "admin-course-group-type-view",
  admin_company_get_holiday_list: "admin-company-get-holiday-list",
  admin_company_get_holiday_one: "admin-company-get-holiday-one",
  admin_company_holiday_view_with_group:
    "admin-company-holiday-view-with-group",
  lead_config_sms_template: "lead-config-sms-template",
  lead_config_sms_history: "lead-config-sms-history",
  lead_config_sms_template_one: "lead-config-sms-template-one",
  lead_list: "lead-list",
  admin_lead_statistics_by_admin: "admin_lead_statistics_by_admin",
  lead_history: "lead-history",
  lead_tabs: "lead-tabs",
  lead_created_by: "lead-created-by",
  lead: "lead",
  lead_call_history: "lead_call_history",
  admin_call_operator_calls: "admin_call_operator_calls",
  admin_company_leaving_category_index: "admin-company-leaving-category-index",
  admin_course_lesson_day_index: "admin-course-lesson-day-index",
  admin_course_lesson_day_view: "admin-course-lesson-day-view",
  admin_course_level_index: "admin-course-level-index",
  admin_company_life_cycle_page_data: "admin-company-life-cycle-page-data",
  admin_company_life_cycle: "admin-company-life-cycle",
  admin_company_life_cycle_view: "admin-company-life-cycle-view",
  admin_call_operator_list: "admin-call-operator-list",
  admin_call_page_data: "admin_call_page_data",
  admin_call_cron_index: "admin_call_cron_index",
  admin_get_call_template: "admin_get_call_template",
  admin_call_template_view: "admin_call_template_view",
  admin_call_operator_view: "admin-call-operator-view",
  gc_page_data: "gc-page-data",
  page_data: "page-data",
  admin_grouped_modals_calculation: "admin-grouped-modals-calculation",
  admin_finance_dispersion: "admin-finance-dispersion",
  get_payment_page_data: "get-payment-page-data",
  admin_finance_payment_statistics_index:
    "admin-finance-payment-statistics-index",
  admin_finance_payment_statistics_group:
    "admin-finance-payment-statistics-group",
  regions_list: "regions-list",
  region_list: "region-list",
  role_page_data: "role-page-data",
  role_one: "role-one",
  rooms_list: "rooms-list",
  room_list: "room-list",
  task_enums: "task-enums",
  task_single: "task-single",
  staff_initial_data: "staff-initial-data",
  registering_list_view: "registering-list-view",
  task_view: "task-view",
  task_categories: "task-categories",
  task_admin_users: "task-admin-users",
  task_users: "task-users",
  task_admin_category_index: "task-admin-category-index",
  admin_task_task_category_view: "admin-task-task-category-view",
  task_index: "task-index",
  task_responsible_by_filter: "task-responsible-by-filter",
  task_can_assign_responsible: "task-can-assign-responsible",
  task_can_assign_myself: "task-can-assign-myself",
  admin_finance_salary_main_index: "admin-finance-salary-main-index",
  admin_finance_salary_branch_main_index:
    "admin_finance_salary_branch_main_index",
  admin_finance_salary_cover_index: "admin-finance-salary-cover-index",
  admin_finance_salary_cover_view: "admin-finance-salary-cover-view",
  admin_finance_salary_cover_page_data: "admin-finance-salary-cover-page-data",
  admin_v1_secret_client_cycle_view:
    "admin-admin_v1_secret_client_cycle_view-salary-cover-page-data",
  admin_finance_salary_salary_component_page_data:
    "admin-finance-salary-salary-component-page-data",
  admin_v1_finance_salary_detailed_cover_config_page_data:
    "admin_v1_finance_salary_detailed_cover_config_page_data",
  admin_v1_finance_salary_detailed_cover_form_data:
    "admin_v1_finance_salary_detailed_cover_form_data",
  admin_v1_finance_salary_detailed_cover_index:
    "admin_v1_finance_salary_detailed_cover_index",
  sms_page_data: "sms-page-data",
  sms_statistics_page_data: "sms-statistics-page-data",
  admin_statistics_dashboard_statistics_group:
    "admin-statistics-dashboard-statistics-group",
  sms_template: "sms-template",
  sms_template_one: "sms-template-one",
  admin_company_get_source_list: "admin-company-get-source-list",
  admin_company_get_source_view: "admin-company-get-source-view",
  main_card: "main-card",
  sms_list: "sms-list",
  kpi_statistics: "kpi-statistics",
  staff_motivation: "staff-motivation",
  income_lost: "orderTabs-lost",
  freshman_lost_page_data: "freshman-lost-page-data",
  lost_list: "lost-list",
  freshman_list: "freshman-list",
  admin_statistics_podo_index: "admin-statistics-podo-index",
  teacher_lost_list: "teacher-lost-list",
  student_statistics: "student-statistics",
  new_student_statistics: "new-student-statistics",
  waiting_list_statistics: "waiting-list-statistics",
  lead_statistics: "lead-statistics",
  by_native_language_statistics: "by-native-language-statistics",
  by_gender_statistics: "by-gender-statistics",
  income_statistics: "orderTabs-statistics",
  sms_counts: "sms-counts",
  admin_student_payment: "admin-student-payment",
  admin_student_call: "admin-student-call",
  system_student_profile_skill: "system_student_profile_skill",
  system_student_profile_exam: "system_student_profile_exam",
  student_search_one: "student-search-one",
  admin_student_sms: "admin-student-sms",
  system_student_profile_topic_words_count:
    "system_student_profile_topic_words_count",
  admin_student_group: "admin-student-group",
  admin_student_life_cycle: "admin-student-life-cycle",
  student_balance: "student-balance",
  student_balance_dashboard: "student-balance-dashboard",
  student_balance_transactions: "student_balance_transactions",
  student_balance_dashboard_transactions_stats:
    "student-balance-dashboard-transactions-stats",
  move_validate: "move-validate",
  admin_grouped_group_contact_index: "admin-grouped-group-contact-index",
  get_one_student: "get-one-student",
  search_one_ars: "search-one-ars",
  studying_student_list: "studying-student-list",
  debtor_student_list: "debtor-student-list",
  admin_student_archive_list: "admin-student-archive-list",
  transfer_page_data: "transfer-page-data",
  transfer_calc: "transfer-calc",
  validate_transfer: "validate-transfer",
  admin_grouped_group_contact_attendance_control:
    "admin-grouped-group_contact-attendance-control",
  admin_abs_group_list: "admin-abs-group-list",
  admin_missed_attendance_group: "admin-missed-attendance-group",
  route_params: "route-params",
  waiting_list: "waiting-list",
  dob_list: "dob-list",
  admin_student_recommendation: "admin-student-recommendation",
  recommendation: "recommendation",
  admin_company_leaving_category_view: "admin-company-leaving-category-view",
  global_search: "global-search",
  system_group_preview_date: "system-group-preview-date",
  config_vacancy_index: "config_vacancy_index",
  vacancy_page_data: "vacancy_page_data",
  admin_event_index: "admin_event_index",
  pixel_page_data: "pixel_page_data",
  admin_rbac_role_permissions: "admin_rbac_role_permissions",
  applicant_status_list: "applicant_status_list",
  applicant_main_index: "applicant_main_index",
  candidate_model_data: "candidate_model_data",
  download_meeting: "download_meeting",
  hr_initial_data: "hr_initial_data",
  meeting_days: "meeting_days",
  approve_info: "approve_info",
  candidate_lifecycle: "candidate_lifecycle",
  admin_v1_secret_client_cycle_index: "admin_v1_secret_client_cycle_index",
  admin_v1_secret_client_cycle_create: "admin_v1_secret_client_cycle_create",
  admin_v1_main_general_get_meeting_responsible:
    "admin_v1_main_general_get_meeting_responsible",
  admin_company_current: "admin_company_current",
  admin_academic_fallible_index: "admin_academic_fallible_index",
  firebase_query: "firebase_query",
  get_my_web_notifications: "get_my_web_notifications",
  get_staff_lifecycle: "get_staff_lifecycle",
  get_rewards: "get_rewards",
  get_notification_by_id: "get_notification_by_id",
  admin_task_task_index: "admin_task_task_index",
  admin_main_general_search_by_phone: "admin_main_general_search_by_phone",
  admin_statistics_created_student: "admin_statistics_created_student",
  admin_exam_info_pass_rate_teacher: "admin_exam_info_pass_rate_teacher",
  admin_mock_exam_info_pass_rate_teacher:
    "admin_mock_exam_info_pass_rate_teacher",
  admin_exam_info_exam_progress: "admin_exam_info_exam_progress",
  admin_grouped_group_contact_absent_student_by_mentor:
    "admin_grouped_group_contact_absent_student_by_mentor",
};
