.deploy_template:
  stage: deploy
  image: registry.inter-nation.uz/infrastructure/docker:helm-dind
  script:
    - echo $K8SCONFIGJSON > tmp
    - yq -P tmp > /root/.kube/config
    - chmod 600 /root/.kube/config
    - DEPLOYMENT=$(echo $CI_PROJECT_NAME | sed s/_/-/g | sed s/$CI_PROJECT_NAMESPACE-//g)
    - helm repo add --username $HELM_REGISTRY_USERNAME --password $HELM_REGISTRY_PASSWORD $HELM_REPO_NAME $HELM_REGISTRY_PATH
    - helm upgrade --install $DEPLOYMENT-$SOURCE $HELM_REPO_NAME/$HELM_CHART_NAME --set=image.source=$SOURCE --set=image.tag=$CI_PIPELINE_IID --values $VALUES_FILE -n $NAMESPACE
